### ISSUE TITLE
Nastavení pozice ve stránce po validaci formuláře

### ISSUE THREAD

**Issue by premyslposker** [peckadesign/pdForms#1]
Po validaci formuláře a zobrazení chybových hlášek by se hodila možnost nastavení pozice tak, aby bylo možné vidět chybové hlášky, které se zobrazují např. v globálním kontejneru, který je obvykle nad prvním formulářovým prvek, které obsahuje chybu.

**Comment by zipper** [comment]
Vyřešeno v releasu [4.1.0](https://github.com/peckadesign/pdForms/releases/tag/v4.1.0).
