### ISSUE TITLE
Rozšíření o možnost používat dostupná Nette pravidla jako nepovinná

### ISSUE THREAD

**Issue by klobinoid** [peckadesign/pdForms#20]
- dodělat do v2 i v3
- přepsat patternová pravidla interně na nette pattern validátory (contains number, phone)

**Comment by zipper** [comment]
Toto je afaik již realizováno a releasnuto v https://github.com/peckadesign/pdForms/releases/tag/3.0.1, respektive https://github.com/peckadesign/pdForms/releases/tag/2.0.2.
