### ISSUE TITLE
Nezobrazení validační zprávy v IE11

### ISSUE THREAD

**Issue by zipper** [peckadesign/pdForms#24]
IE11 a starší nepodporují `ParentNode.prepend()` a `ParentNode.append()`, proto v nich dojde k JS chybě a validační zpráva se nikde neozbrazí.

**Comment by zipper** [comment]
@sebastianvass Prosím o otestování vypisování validačních zpráv, především v IE11, ale pro kontrolu i v Chrome. V profilu na poli pro e-mail je pro účely testování nastaveno připojení validační zprávy před input. Prosím o otestování i např. v dopravě a platbě, kde je trochu jiný styl připojování.

- hotovo ve větvi `pdforms-24-validace-v-ie`
- PR projekt https://github.com/peckadesign/Gant2017/pull/2422
- K testování na http://test2422.gant2017.peckadesign.com

Pro porovnání na tomto testu by v IE vypsání validačních zpráv nemělo fungovat  vůbec http://test2156.gant2017.peckadesign.com.

**Comment by sebastianvass** [comment]
Otestoval som to na chrome a IE a je to zamna ok. Porovnal som to voči tomu testu kde to predtým nešlo a je to ok.

**Comment by zipper** [comment]
https://github.com/peckadesign/pdForms/releases/tag/3.0.3
