### ISSUE TITLE
Nefunkční Nette.initForm

### ISSUE THREAD

**Issue by zipper** [peckadesign/pdForms#26]
Ve vzácných případech mohlo dojít k situace, že `Nette.initForm` způsobila chybu  v případě AJAXové validace. Výjimečně mohlo dojít k tomu, že JS událost `DOMContentLoaded` byla vyvolána dříve, než dojde ke zpracování již staženého JS. V tu chvíli event handler vyvolat inicializaci formuláře, která prostředníctvím `Nette.toggleForm` spustila AJAXovou validaci ve chvíli, kdy ještě `$.nette` bylo `undefined`.

**Comment by zipper** [comment]
Prosím @petrgala a @sebastianvass ještě jednou otestování, jde o onu chybu po přihlášení v objednávce, kdy nefungovalo rozbalování prvků, díky.

Projektový PR:
- hotovo ve větvi `pdforms-26-oprava-ajax-validaci-pri-initForm`
- PR projekt https://github.com/peckadesign/Gant2017/pull/2423
- K testování na http://test2423.gant2017.peckadesign.com

**Comment by petrgala** [comment]
@zipper vyzkoušel jsem, chyba se mi už neprojevila

**Comment by sebastianvass** [comment]
@zipper Taktiež som sa na to pozrel a už je to za mna ok.

**Comment by zipper** [comment]
https://github.com/peckadesign/pdForms/releases/tag/3.0.4

**Comment by zipper** [comment]
Podmínka pro otestování přítomnosti `$` vyhazuje pro změnu jinou chybu do konzole.

Vyřešeno ve větvi `26-initForm-2`, PR https://github.com/peckadesign/pdForms/pull/29.

**Comment by zipper** [comment]
Opraveno v release https://github.com/peckadesign/pdForms/releases/tag/3.0.5
